# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: ShadiAlrashoodi.Booth
PackageVersion: 0.2.2
MinimumOSVersion: 10.0.19041.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{87DFEF29-7B44-4A76-8F33-43BA1EF8F04D}_is1'
ReleaseDate: 2026-10-08
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Shadi-Alrashoodi/booth/releases/download/v0.2.2/booth-0.2.2-setup.exe
  InstallerSha256: 2F2FB44EC962AB74BAFB7C8765E2725B276B73AE74055E2031B46BF2D689991A
ManifestType: installer
ManifestVersion: 1.12.0
